package net.CyanWool.api.entity;

public enum EntityType {
    CREEPER, SKELETON, SPIDER, GIANT_ZOMBIE, ZOMBIE, SLIME, GHAST, ZOMBIE_PIGMAN, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, ENDER_DRAGON, WITHER, BAT, WITCH, ENDERMITE, GUARDIAN, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MOOSHROOM, SNOWMAN, OCELOT, IRON_GOLEM, HORSE, RABBIT, VILLAGER, PLAYER, NONE;
}