package net.CyanWool.api.world;

public enum Effect {
    PLAY_RECORD, SMOKE, BREAK_BLOCK, BREAK_SPLASH_POTION, BREAK_EYE_OF_ENDER, MOB_SPAWN, BONEMEAL_GROW, HARD_LANDING_DUST, CLICK, EMPTY_DISPENSER_CLICK, FIRE_PROJECTILE, DOOR, FIZZLE, GHAST_CHARGE, GHAST_FIRE, BLAZE_FIRE, POUND_WOODEN_DOOR, POUND_METAL_DOOR, BREAK_WOODEN_DOOR, WITHER_SPAWN, WITHER_SHOOT, BAT_TAKE_OFF, INFECT_VILLAGER, DISINFECT_VILLAGER, ENDER_DRAGON_DEATH, ANVIL_BREAK, ANVIL_USE, ANVIL_LAND;
    ;}